(()=>{"use strict";
const KEY="voiceMemoPrototypeV1",SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
const recordButton=document.querySelector("#record-button"),recordLabel=document.querySelector("#record-label"),status=document.querySelector("#status"),statusText=document.querySelector("#status-text"),supportMessage=document.querySelector("#support-message"),transcript=document.querySelector("#transcript"),saveButton=document.querySelector("#save-button"),clearButton=document.querySelector("#clear-button"),feedback=document.querySelector("#feedback"),memoList=document.querySelector("#memo-list"),memoCount=document.querySelector("#memo-count"),memoTemplate=document.querySelector("#memo-template");
let recognition=null,isRecording=false,baseText="",sessionResults=[],sessionFinalText="",shouldRestart=false;
function readMemos(){try{const data=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(data)?data:[]}catch{return[]}}
function writeMemos(memos){localStorage.setItem(KEY,JSON.stringify(memos))}
function formatDate(date){return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(date))}
function renderMemos(){const memos=readMemos().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));memoCount.textContent=`${memos.length}件`;memoList.replaceChildren();if(!memos.length){const empty=document.createElement("p");empty.className="empty-state";empty.textContent="保存したメモはまだありません。\n録音して最初のメモを残しましょう。";memoList.append(empty);return}const list=document.createElement("div");list.className="memo-list";memos.forEach(memo=>{const card=memoTemplate.content.firstElementChild.cloneNode(true),time=card.querySelector(".memo-date");time.dateTime=memo.createdAt;time.textContent=formatDate(memo.createdAt);card.querySelector(".memo-text").textContent=memo.text;card.querySelector(".delete-button").addEventListener("click",()=>{writeMemos(readMemos().filter(item=>item.id!==memo.id));renderMemos();showFeedback("メモを削除しました")});list.append(card)});memoList.append(list)}
function setRecordingUI(value){isRecording=value;recordButton.classList.toggle("is-recording",value);recordButton.setAttribute("aria-pressed",String(value));status.classList.toggle("is-recording",value);recordLabel.textContent=value?"録音停止":"録音開始";statusText.textContent=value?"録音中… 話してください":"タップして話してください"}
function showFeedback(message){feedback.textContent=message;clearTimeout(showFeedback.timer);showFeedback.timer=setTimeout(()=>feedback.textContent="",2600)}function updateSaveState(){saveButton.disabled=!transcript.value.trim()}
function composeFinalText(){return sessionResults.filter(result=>result?.isFinal).map(result=>result.text).reduce((state,text)=>{if(!text||text===state.previous)return state;if(state.previous&&text.startsWith(state.previous)){state.text=`${state.text.slice(0,-state.previous.length)}${text}`}else if(!state.text.endsWith(text)){state.text+=`${state.text?" ":""}${text}`}state.previous=text;return state},{text:"",previous:""}).text}
function renderRecognition(includeInterim=true){sessionFinalText=composeFinalText();const interimText=includeInterim?sessionResults.filter(result=>result&&!result.isFinal).map(result=>result.text).join(" "):"";transcript.value=`${baseText}${sessionFinalText}${interimText?`${sessionFinalText?" ":""}${interimText}`:""}`.trimStart();updateSaveState()}
function stopRecording(){shouldRestart=false;if(recognition&&isRecording)recognition.stop();renderRecognition(false);setRecordingUI(false)}
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang="ja-JP";recognition.continuous=true;recognition.interimResults=true;recognition.addEventListener("start",()=>setRecordingUI(true));recognition.addEventListener("result",event=>{sessionResults.length=event.results.length;for(let i=event.resultIndex;i<event.results.length;i++){const result=event.results[i],recognizedText=result[0].transcript.trim().replace(/\s+/g," ");sessionResults[i]={text:recognizedText,isFinal:result.isFinal}}renderRecognition(true)});recognition.addEventListener("end",()=>{renderRecognition(false);if(shouldRestart){baseText=transcript.value.trim();if(baseText)baseText+=" ";sessionResults=[];sessionFinalText="";try{recognition.start()}catch{setRecordingUI(false)}}else setRecordingUI(false)});recognition.addEventListener("error",event=>{shouldRestart=false;renderRecognition(false);setRecordingUI(false);const messages={"not-allowed":"マイクの使用が許可されていません。ブラウザの設定を確認してください。","audio-capture":"マイクを利用できません。端末のマイク設定を確認してください。","no-speech":"音声を認識できませんでした。もう一度お試しください。",network:"音声認識に接続できませんでした。通信状態を確認してください。"};supportMessage.textContent=messages[event.error]||"音声認識でエラーが発生しました。";supportMessage.classList.add("is-error")});recordButton.addEventListener("click",()=>{supportMessage.classList.remove("is-error");supportMessage.textContent="音声は文字としてメモに追加されます";if(isRecording){stopRecording();return}baseText=transcript.value.trim();if(baseText)baseText+=" ";sessionResults=[];sessionFinalText="";shouldRestart=true;try{recognition.start()}catch{shouldRestart=false;supportMessage.textContent="音声認識を開始できませんでした。少し待って再度お試しください。";supportMessage.classList.add("is-error")}})}else{recordButton.disabled=true;recordButton.setAttribute("aria-disabled","true");recordButton.style.opacity=".55";statusText.textContent="音声認識は利用できません";supportMessage.textContent="このブラウザでは音声認識を利用できません";supportMessage.classList.add("is-error")}
transcript.addEventListener("input",()=>{baseText=transcript.value;sessionResults=[];sessionFinalText="";updateSaveState()});clearButton.addEventListener("click",()=>{if(isRecording)stopRecording();transcript.value="";baseText="";sessionResults=[];sessionFinalText="";updateSaveState();transcript.focus()});saveButton.addEventListener("click",()=>{const text=transcript.value.trim();if(!text)return;if(isRecording)stopRecording();const memos=readMemos();memos.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,text,createdAt:new Date().toISOString()});writeMemos(memos);transcript.value="";baseText="";sessionResults=[];sessionFinalText="";updateSaveState();renderMemos();showFeedback("メモを保存しました")});renderMemos();updateSaveState();if("serviceWorker"in navigator&&location.protocol!=="file:")window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));
})();
