(()=>{"use strict";
const KEY="voiceMemoPrototypeV1",SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
const recordButton=document.querySelector("#record-button"),recordLabel=document.querySelector("#record-label"),status=document.querySelector("#status"),statusText=document.querySelector("#status-text"),supportMessage=document.querySelector("#support-message"),transcript=document.querySelector("#transcript"),saveButton=document.querySelector("#save-button"),clearButton=document.querySelector("#clear-button"),feedback=document.querySelector("#feedback"),memoList=document.querySelector("#memo-list"),memoCount=document.querySelector("#memo-count"),memoTemplate=document.querySelector("#memo-template");
const diagnosticToggle=document.querySelector("#diagnostic-toggle"),diagnosticPanel=document.querySelector("#diagnostic-panel"),diagnosticLog=document.querySelector("#diagnostic-log");
let recognition=null,isRecording=false,baseText="",sessionResults=[],sessionFinalText="",diagnosticEntries=[],currentFilter="all",shouldRestart=false;
function readMemos(){try{const data=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(data)?data:[]}catch{return[]}}
function writeMemos(memos){localStorage.setItem(KEY,JSON.stringify(memos))}
function formatDate(date){return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(date))}
function updateMemo(id,changes){writeMemos(readMemos().map(memo=>memo.id===id?{...memo,...changes}:memo))}
function renderMemos(){const allMemos=readMemos().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)),memos=allMemos.filter(memo=>currentFilter==="all"||(currentFilter==="completed"?Boolean(memo.completed):!memo.completed));memoCount.textContent=`${memos.length}件`;memoList.replaceChildren();if(!memos.length){const empty=document.createElement("p");empty.className="empty-state";empty.textContent=allMemos.length?"この条件に一致するメモはありません。":"保存したメモはまだありません。\n録音して最初のメモを残しましょう。";memoList.append(empty);return}const list=document.createElement("div");list.className="memo-list";memos.forEach(memo=>{const card=memoTemplate.content.firstElementChild.cloneNode(true),time=card.querySelector(".memo-date"),text=card.querySelector(".memo-text"),editor=card.querySelector(".edit-textarea"),statusButton=card.querySelector(".status-button"),memoActions=card.querySelector(".memo-actions"),editActions=card.querySelector(".edit-actions"),completed=Boolean(memo.completed);card.classList.toggle("is-completed",completed);time.dateTime=memo.createdAt;time.textContent=formatDate(memo.createdAt);text.textContent=memo.text;editor.value=memo.text;statusButton.textContent=completed?"完了":"未対応";statusButton.classList.toggle("is-completed",completed);statusButton.setAttribute("aria-label",completed?"完了済み。未対応に戻す":"未対応。完了にする");statusButton.addEventListener("click",()=>{updateMemo(memo.id,{completed:!completed});renderMemos();showFeedback(completed?"未対応に戻しました":"完了にしました")});card.querySelector(".edit-button").addEventListener("click",()=>{text.hidden=true;editor.hidden=false;memoActions.hidden=true;editActions.hidden=false;editor.focus();editor.setSelectionRange(editor.value.length,editor.value.length)});card.querySelector(".cancel-edit-button").addEventListener("click",()=>renderMemos());card.querySelector(".save-edit-button").addEventListener("click",()=>{const editedText=editor.value.trim();if(!editedText){editor.focus();return}updateMemo(memo.id,{text:editedText});renderMemos();showFeedback("メモを更新しました")});card.querySelector(".delete-button").addEventListener("click",()=>{if(!window.confirm("このメモを削除しますか？"))return;writeMemos(readMemos().filter(item=>item.id!==memo.id));renderMemos();showFeedback("メモを削除しました")});list.append(card)});memoList.append(list)}
function setRecordingUI(value){isRecording=value;recordButton.classList.toggle("is-recording",value);recordButton.setAttribute("aria-pressed",String(value));status.classList.toggle("is-recording",value);recordLabel.textContent=value?"録音停止":"録音開始";statusText.textContent=value?"録音中… 話してください":"タップして話してください"}
function showFeedback(message){feedback.textContent=message;clearTimeout(showFeedback.timer);showFeedback.timer=setTimeout(()=>feedback.textContent="",2600)}function updateSaveState(){saveButton.disabled=!transcript.value.trim()}
function comparisonKey(text){return text.trim().toLocaleLowerCase("ja-JP").replace(/[\s、。,.，．！？!?「」『』（）()［］\[\]【】・:：;；]+/g,"")}
function composeFinalText(){return sessionResults.filter(result=>result?.isFinal).map(result=>result.text).reduce((segments,text)=>{const key=comparisonKey(text);if(!key)return segments;const currentKey=comparisonKey(segments.map(segment=>segment.text).join(" "));if(key===currentKey||currentKey.includes(key))return segments;if(currentKey&&key.startsWith(currentKey))return [{text,key}];const last=segments.at(-1);if(last&&(key===last.key||last.key.includes(key)))return segments;if(last&&key.startsWith(last.key)){segments[segments.length-1]={text,key};return segments}segments.push({text,key});return segments},[]).map(segment=>segment.text).join(" ")}
function addDiagnosticEntry(event){const entries=[];for(let i=event.resultIndex;i<event.results.length;i++){const result=event.results[i];entries.push(`resultIndex: ${event.resultIndex}\nresult[${i}].transcript: ${result[0].transcript}\nresult[${i}].isFinal: ${result.isFinal}\n現在の確定文: ${sessionFinalText||"（なし）"}`)}diagnosticEntries.push(...entries);diagnosticEntries=diagnosticEntries.slice(-80);diagnosticLog.textContent=diagnosticEntries.join("\n---\n")||"認識イベントはまだありません。"}
function renderRecognition(includeInterim=true){sessionFinalText=composeFinalText();const interimText=includeInterim?sessionResults.filter(result=>result&&!result.isFinal).map(result=>result.text).join(" "):"";transcript.value=`${baseText}${sessionFinalText}${interimText?`${sessionFinalText?" ":""}${interimText}`:""}`.trimStart();updateSaveState()}
function stopRecording(){shouldRestart=false;if(recognition&&isRecording)recognition.stop();renderRecognition(false);setRecordingUI(false)}
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang="ja-JP";recognition.continuous=true;recognition.interimResults=true;recognition.addEventListener("start",()=>setRecordingUI(true));recognition.addEventListener("result",event=>{sessionResults.length=event.results.length;for(let i=event.resultIndex;i<event.results.length;i++){const result=event.results[i],recognizedText=result[0].transcript.trim().replace(/\s+/g," ");sessionResults[i]={text:recognizedText,isFinal:result.isFinal}}renderRecognition(true);addDiagnosticEntry(event)});recognition.addEventListener("end",()=>{renderRecognition(false);if(shouldRestart){baseText=transcript.value.trim();if(baseText)baseText+=" ";sessionResults=[];sessionFinalText="";try{recognition.start()}catch{setRecordingUI(false)}}else setRecordingUI(false)});recognition.addEventListener("error",event=>{shouldRestart=false;renderRecognition(false);setRecordingUI(false);const messages={"not-allowed":"マイクの使用が許可されていません。ブラウザの設定を確認してください。","audio-capture":"マイクを利用できません。端末のマイク設定を確認してください。","no-speech":"音声を認識できませんでした。もう一度お試しください。",network:"音声認識に接続できませんでした。通信状態を確認してください。"};supportMessage.textContent=messages[event.error]||"音声認識でエラーが発生しました。";supportMessage.classList.add("is-error")});recordButton.addEventListener("click",()=>{supportMessage.classList.remove("is-error");supportMessage.textContent="音声は文字としてメモに追加されます";if(isRecording){stopRecording();return}baseText=transcript.value.trim();if(baseText)baseText+=" ";sessionResults=[];sessionFinalText="";diagnosticEntries=[];diagnosticLog.textContent="認識イベントはまだありません。";shouldRestart=true;try{recognition.start()}catch{shouldRestart=false;supportMessage.textContent="音声認識を開始できませんでした。少し待って再度お試しください。";supportMessage.classList.add("is-error")}})}else{recordButton.disabled=true;recordButton.setAttribute("aria-disabled","true");recordButton.style.opacity=".55";statusText.textContent="音声認識は利用できません";supportMessage.textContent="このブラウザでは音声認識を利用できません";supportMessage.classList.add("is-error")}
document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{currentFilter=button.dataset.filter;document.querySelectorAll("[data-filter]").forEach(filterButton=>{const active=filterButton===button;filterButton.classList.toggle("is-active",active);filterButton.setAttribute("aria-pressed",String(active))});renderMemos()}));
diagnosticToggle.addEventListener("click",()=>{const willOpen=diagnosticPanel.hidden;diagnosticPanel.hidden=!willOpen;diagnosticToggle.setAttribute("aria-expanded",String(willOpen));diagnosticToggle.textContent=willOpen?"診断を閉じる":"音声認識の診断"});
transcript.addEventListener("input",()=>{baseText=transcript.value;sessionResults=[];sessionFinalText="";updateSaveState()});clearButton.addEventListener("click",()=>{if(isRecording)stopRecording();transcript.value="";baseText="";sessionResults=[];sessionFinalText="";updateSaveState();transcript.focus()});saveButton.addEventListener("click",()=>{const text=transcript.value.trim();if(!text)return;if(isRecording)stopRecording();const memos=readMemos();memos.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,text,createdAt:new Date().toISOString(),completed:false});writeMemos(memos);transcript.value="";baseText="";sessionResults=[];sessionFinalText="";updateSaveState();renderMemos();showFeedback("メモを保存しました")});renderMemos();updateSaveState();if("serviceWorker"in navigator&&location.protocol!=="file:")window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));
})();
